name: cable_burial_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - numpy
  - richdem
  - pyproj
  - shapely
  - fiona
  - rasterio
  - jupyterlab
  - notebook
